<form method="post" class="fancyform">

    <?php foreach ($form->getControls() as $control) : ?>
        <div>
            <?php $control->render(); ?>
        </div>
    <?php endforeach ?>

    <?php foreach ($form->getButtons() as $button) : ?>
        <div>
            <?php $button->render(); ?>
        </div>
    <?php endforeach ?>

    <input type="hidden" name="_id" value="<?= $form->formName ?>">
</form>